name: QSY_client
description: A new Flutter project for VPN client

publish_to: 'none' # Remove this line if you intend to publish to pub.dev

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.0.0
  shared_preferences: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
